spring:
  datasource:
    url: jdbc:postgresql://${DEV_DB_HOST}/${DEV_DB_NAME}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cors:
  allowed-origins: "http://localhost:3000"

socket:

server:
  port: 8000

whatsapp:
  access-token: ${WHATSAPP_ACCESS_TOKEN}
  phone-number-id: ${PHONE_NUMBER_ID}
  version: ${VERSION:v21.0}
  kitchen-phones: "48512066441"

#logging:
#  level:
#    org.springframework.messaging.simp.stomp: DEBUG
#    org.springframework.web.socket: DEBUG
#    org.springframework.web.socket.sockjs: DEBUG

#jahez:
#  base-url: https://integration-api-staging.jahez.net